# Generated by Django 3.1 on 2021-12-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calculadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operando_1', models.IntegerField()),
                ('operador', models.CharField(blank=True, choices=[('+', 'Soma'), ('-', 'Subtração'), ('*', 'Multiplicação'), ('/', 'Divisão')], max_length=1, null=True)),
                ('operando_2', models.IntegerField()),
                ('resposta', models.IntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
        ),
    ]
